### ISSUE TITLE
Kube: restrict the rights

### ISSUE THREAD

**Issue by severo** [huggingface/datasets-server#240]
In the deployments, run with a non root user:

```
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
```

Beware: just adding this generates errors (Permission denied) when trying to write to the mounted volumes. We have to mount with writing rights for the user
