### ISSUE TITLE
Make dataset viewer configurable

### ISSUE THREAD

**Issue by polinaeterna** [huggingface/datasets-server#2639]
Some examples of potential usages:
- specify that a string column should be treated as a class
- specify columns order
- set which config to display by default if it differs from `datasets`' default one.

Maybe in the future, when (i hope) we have more functionality, we can also provide which metrics and over which columns to compute. 

### How to implement
1. We can support a dedicated field in README.md's yaml, something like:
```yaml
---
...
viewer_config:
    default_config: python
    features:
        language: class
        title: string
...
```

2. In datasets-server we can create a dedicated job runner `dataset-viewer-config` that would store this information. Or store this along with the `*-info` steps but this way it would be exposed in `/info` endpoint which is probably unnecessary.

wdyt @AndreaFrancis @severo @lhoestq @albertvillanova ?
